name: publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          path: gitinfo-lua
          fetch-tags: true
          fetch-depth: 0
      - name: Check out texmf
        uses: actions/checkout@v4
        with:
          repository: Xerdi/texmf-packaging
          path: texmf
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: maclotsen/texlive:with-gf
          shell: bash
          options: --rm -i -v ${{ github.workspace }}/texmf:/root/texmf -v ${{ github.workspace }}:/build
          run: |
            git config --global --add safe.directory /build/gitinfo-lua
            make -C gitinfo-lua package
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          body: |
            Release for version ${{ github.ref_name }}
      - name: 'Upload Release Asset: Tar'
        id: upload_release_asset_tar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/gitinfo-lua/gitinfo-lua-${{ github.ref_name }}.tar.gz
          asset_name: gitinfo-lua-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
      - name: 'Upload Release Asset: Manual'
        id: upload_release_asset_manual
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/gitinfo-lua/doc/gitinfo-lua.pdf
          asset_name: gitinfo-lua-${{ github.ref_name }}.pdf
          asset_content_type: application/pdf
